name: Dynmap-PreciousStones
main: net.dandielo.dynmap.preciousstones.DynmapPreciousStones
version: 1.2.1 Release
author: dandielo
softdepend: [ dynmap, PreciousStones ]
commands:
  map:
    description: Map commands
    usage: Syntax error, verify the command usage and try again
permissions:
  simpleclans.map.toggle:
    description: Can toggle map visibility
